---
#   $$\      $$\                     $$\       $$\                    
#   $$ | $\  $$ |                    $$ |      $$ | $$$$$$$\                            $$\                 
#   $$ |$$$\ $$ | $$$$$$\   $$$$$$\  $$ | $$$$$$$ | $$  __$$\                           $$ |     
#   $$ $$ $$\$$ |$$  __$$\ $$  __$$\ $$ |$$  __$$ | $$ |  $$ | $$$$$$\   $$$$$$\   $$$$$$$ | $$$$$$\   $$$$$$\  
#   $$$$  _$$$$ |$$ /  $$ |$$ |  \__|$$ |$$ /  $$ | $$$$$$$\ |$$  __$$\ $$  __$$\ $$  __$$ |$$  __$$\ $$  __$$\ 
#   $$$  / \$$$ |$$ |  $$ |$$ |      $$ |$$ |  $$ | $$  __$$\ $$ /  $$ |$$ |  \__|$$ /  $$ |$$$$$$$$ |$$ |  \__|   
#   $$  /   \$$ |\$$$$$$  |$$ |      $$ |\$$$$$$$ | $$ |  $$ |$$ |  $$ |$$ |      $$ |  $$ |$$   ____|$$ |   
#   \__/     \__| \______/ \__|      \__| \_______| $$$$$$$  |\$$$$$$  |$$ |      \$$$$$$$ |\$$$$$$$\ $$ |           
#          PocketMine World Border Plugin           \_______/  \______/ \__|       \_______| \_______|\__|                                                                                                           

# Version- Don't Change!
version: 1.0.0

# Important Note to EVERYONE:
# The border will set whatever your distance is away from the world spawn. Say my world spawn = 300, 56, 300 and my border size = 700. 
# The border will extend 175 from 300, meaning the "border" would be:  -475 ----- 125
#                                                                       |           |     # This meaning it expands 175 blocks in all directions
#    WorldBorder Plugin                                                 |  300,300  |     # If the border was 20, it would again expand 5 blocks each way
#    Download: https://github.com/Pinesolz/WorldBorder                  |           |     # WorldBorder does NOT effect height.
#    Author: Soulz                                                     -125 ----- 475     # The border is circular! Diagram is just a rough sketch.

border: 
  world: 700 # Border World and Size of Border. 
             # Selected World also Teleports Players to World's Default Spawn or Player Spawn Point. (If /setplayer spawn is executed, or bed is used)
  border-message: "§l§cError: §r§7You've reached the world border!"

# For colour, use symbol: & , §
    # Red = §4, §c
    # Gold = §6
    # Yellow = §e
    # Dark Green = §2
    # Green = §a
    # Aqua = §b
    # Dark Aqua = §3
    # Dark Blue = §1
    # Blue = §9
    # Light Purple = §d
    # Dark Purple = §5
    # White = §f
    # Gray = §7
    # Dark Gray = §8
    # Black = §0
# Other Format Codes:
    # Obfuscated = §k
    # Bold = §l
    # Italic = §o
    # Reset = §r
...
